name: Security Scan Docker Packages
run-name: >
  Security Scan
on:
  workflow_dispatch:
    inputs:
      only-high-critical:
        description: "Scope only HIGH + CRITICAL"
        required: false
        default: true
        type: boolean
      trivy-scan:
        description: "Trivy scan"
        required: false
        default: true
        type: boolean
      grype-scan:
        description: "Grype scan"
        required: false
        default: true
        type: boolean
      continue-on-error:
        description: "Continue on error"
        required: false
        default: true
        type: boolean
      only-fixed:
        description: "Ignore unfixed vulnerabilities"
        required: false
        default: true
        type: boolean
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 03:00 UTC
permissions:
  contents: read

env:
  CONFIG_FILE: .github/sec-scan.yaml
jobs:
  debug-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.config.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Read config
        id: config
        run: |
          echo "1. ==================================================================================="
          yq --help
          yq -oj '.' $CONFIG_FILE
          echo "2. ==================================================================================="
          yq -oj '.' $CONFIG_FILE | jq -c 'to_entries | map({repo: .key, image: .value[]}) | {packages: .}'
          echo "3. ==================================================================================="

          packages=$(yq -oj '.' $CONFIG_FILE | jq -c 'to_entries | map({repo: .key, image: .value[]})')
          echo "packages=$packages" >> $GITHUB_OUTPUT

  security-scan-matrix:
    needs: debug-packages
    permissions:
      security-events: write
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        package: "${{ fromJson(needs.debug-packages.outputs.packages) }}"
    name: "Run Security Scan (matrix)"
    uses: netcracker/qubership-workflow-hub/.github/workflows/re-security-scan.yml@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
    with:
      target: 'docker'
      image: ${{ matrix.package.image }}

  create-report:
    needs: [security-scan-matrix]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: repo
          persist-credentials: true
          ref: gh_pages
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: '*.sarif'
          path: ./sarif
          merge-multiple: true

      - name: Install CSV-KIT
        run: |
          # sudo apt-get update
          cargo install csv2html
          # sudo apt-get -y install csvkit

      - name: Print packages
        run: |
          mkdir -p repo/html
          for f in $(find ./sarif -name *.csv); do
            csv2html -o repo/docs/$(basename ${f/.csv}).html $f 
          done
          cd repo
          git config --global user.name "$ACTOR"
          git config --global user.email "$ACTOR@users.noreply.github.com"
          git add .
          git commit -m "HTML report ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git push origin "gh_pages"
